#!/bin/bash
#by Joseph Haggerty

if [ $# = 0  ] ; then
	echo -e "\nError, no arguments specified.\n"
	exit 1
fi

if [ $# = 1 ] ; then
	echo -e "\nError, please specify output extension.\n"
	exit 2
fi

if [ $# \> 2 ] ; then
	echo -e "\nError, too many arguments. Only specify 2.\n"
	exit 3
fi

if [ $1 = $2 ] ; then
	echo -e "\nError, input and output extensions are the same.\n"
	exit 4
fi

count=`find . -name "*$1" | wc -l`
if [ $count = 0 ] ; then
	echo -e "\nError, no files exist with that extension. Aborting.\n"
	exit 5
fi

for file in *"$1" ; do
	mv "$file" "${file%$1}$2"
done
